version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/tools/quiz"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/tools/wordcloud"
    schedule:
      interval: "daily"
